# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1074, 755)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.KameraGoruntu = QtWidgets.QLabel(self.centralwidget)
        self.KameraGoruntu.setGeometry(QtCore.QRect(0, 0, 1071, 471))
        self.KameraGoruntu.setText("")
        self.KameraGoruntu.setObjectName("KameraGoruntu")
        self.KameraAc = QtWidgets.QPushButton(self.centralwidget)
        self.KameraAc.setGeometry(QtCore.QRect(10, 490, 141, 51))
        self.KameraAc.setObjectName("KameraAc")
        self.KameraKapat = QtWidgets.QPushButton(self.centralwidget)
        self.KameraKapat.setGeometry(QtCore.QRect(170, 490, 141, 51))
        self.KameraKapat.setObjectName("KameraKapat")
        self.NesneTanima = QtWidgets.QPushButton(self.centralwidget)
        self.NesneTanima.setGeometry(QtCore.QRect(10, 560, 141, 51))
        self.NesneTanima.setObjectName("NesneTanima")
        self.FotografCek = QtWidgets.QPushButton(self.centralwidget)
        self.FotografCek.setGeometry(QtCore.QRect(170, 560, 141, 51))
        self.FotografCek.setObjectName("FotografCek")
        self.Mesajlar = QtWidgets.QListWidget(self.centralwidget)
        self.Mesajlar.setGeometry(QtCore.QRect(695, 471, 381, 231))
        self.Mesajlar.setObjectName("Mesajlar")
        self.FotografEkle = QtWidgets.QPushButton(self.centralwidget)
        self.FotografEkle.setGeometry(QtCore.QRect(10, 630, 141, 51))
        self.FotografEkle.setObjectName("FotografEkle")
        self.VideoEkle = QtWidgets.QPushButton(self.centralwidget)
        self.VideoEkle.setGeometry(QtCore.QRect(170, 630, 141, 51))
        self.VideoEkle.setObjectName("VideoEkle")
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(340, 480, 331, 211))
        self.Logo.setText("")
        self.Logo.setObjectName("Logo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.KameraAc.setText(_translate("MainWindow", "Kamera Aç"))
        self.KameraKapat.setText(_translate("MainWindow", "Kamera Kapat"))
        self.NesneTanima.setText(_translate("MainWindow", "Nesne Tanıma"))
        self.FotografCek.setText(_translate("MainWindow", "Fotoğraf Çek"))
        self.FotografEkle.setText(_translate("MainWindow", "Fotoğraf Seç"))
        self.VideoEkle.setText(_translate("MainWindow", "Video Seç"))
